name: Basic Linux Demo Action
 
on:
  push:
    branches:
      - main
 
jobs:
  linux_actions:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Print Hello Message
        run: echo "Hello world from the Git repository!"
 
      - name: Show current working directoru
        run: pwd
     
      - name: list repository files
        run: ls -ll
     
      - name: create a directroy
        run: mkdir -p output
     
      - name: create a text file
        run: echo "This is a demo file created by the GitHub Action." > output/message.txt
 
      - name: Display the content of the text file
        run: cat output/message.txt
      
      - name: List output directory files
        run: ls -la output
      
      - name: Display multiple messages
        run: |
          echo "Start writing multiple messages"
          echo "Repository: ${{github.repository}}"
          echo "Branch: ${{github.ref_name}}"
          echo "Commit Sha: ${{github.sha}}"
          echo "Trigger: ${{github.actor}}"

      - name: Disk Information
        run: df -h

      - name: System Information
        run: uname -a

      - name: Final message
        run: echo "Github Sction completed successfully"